### ISSUE TITLE
sbt publish-m2

### ISSUE THREAD

**Issue by 765308949** [XiaoMi/pegasus-scala-client#4]
您好，文档上将scala-client安装到本地仓库使用sbt publish-m2，报错指令不存在后使用sbt publishM2，依然报错
 sbt.librarymanagement.ResolveException: unresolved dependency: com.xiaomi.infra#pegasus-client;1.11.5-thrift-0.11.0-inlined: not found

看了一下build文件：
libraryDependencies ++= Seq(
  "com.google.guava" % "guava" % "21.0",
  "com.xiaomi.infra" % "pegasus-client" % "1.11.5-thrift-0.11.0-inlined",
  "org.scalatest" %% "scalatest" % "3.0.3" % Test
)

"com.xiaomi.infra" % "pegasus-client" % "1.11.5-thrift-0.11.0-inlined",
这里能否修改为2.0.0的版本呢？

请问下这种情况应该怎么处理？

**Comment by foreverneverer** [comment]
pegasus-java-client并没有推送到公共仓库，你需要先把[pegasus-java-client](https://github.com/XiaoMi/pegasus-java-client)安装到本地，然后才可以安装pegasus-scala-client
